import {generateDemoData,getTeacherStudents,attendanceSummary,classAttendance,gradeNumber,gradeDisplay,formatPct,SCHOOL_YEAR,GRADES} from './data.mjs';
import {portrait} from './portraits.mjs';
import {applyFacultyDemo,DEFAULT_TEACHER_ID} from './faculty-demo.mjs';
import {latestMapGrowth,mapGrowthSummary,growthFormat} from './map-growth.mjs';
import {renderGrowthProfile,renderGrowthCell} from './map-growth-ui.mjs';

const data=applyFacultyDemo(generateDemoData());
const app=document.getElementById('app');
const state={teacherId:localStorage.getItem('aisg-demo-teacher')||DEFAULT_TEACHER_ID,classId:'all',grade:'all',query:'',subject:'Mathematics',tab:'overview',mobile:false};
const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M9 21v-7h6v7"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="8.5" cy="7" r="4"/><path d="M20 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>',chart:'<path d="M3 3v18h18"/><path d="m7 15 4-4 3 3 5-7"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2"/>',arrow:'<path d="m9 18 6-6-6-6"/>',right:'<path d="M5 12h14m-7-7 7 7-7 7"/>',back:'<path d="m15 18-6-6 6-6"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',info:'<circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/>',target:'<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',activity:'<path d="M22 12h-4l-3 9L9 3l-3 9H2"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',close:'<path d="M18 6 6 18M6 6l12 12"/>',clock:'<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',check:'<path d="m5 12 4 4L19 6"/>',layers:'<rect x="2" y="7" width="20" height="13" rx="2"/><path d="M6 3h12M5 11h14"/>',graduate:'<path d="m2 10 10-5 10 5-10 5-10-5Z"/><path d="M6 12v6c4 3 8 3 12 0v-6M22 10v7"/>',filter:'<path d="M4 7h16M7 12h10M10 17h4"/>',external:'<path d="M15 3h6v6m0-6-10 10"/><path d="M21 13v7H4V4h7"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>'};
const I=(name,size=18)=>`<svg aria-hidden="true" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[name]||icons.info}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const avg=(rows,f)=>rows.length?rows.reduce((a,b)=>a+f(b),0)/rows.length:null;
const teacher=()=>data.teachers.find(x=>x.id===state.teacherId)||data.teachers.find(x=>x.id===DEFAULT_TEACHER_ID);
const allowedStudents=()=>getTeacherStudents(data,teacher());
const allowedClasses=()=>data.classes.filter(c=>teacher().classIds.includes(c.id));
const route=()=>location.hash.replace(/^#\/?/,'')||'overview';
const view=()=>route().startsWith('student/')?'student':route().startsWith('classes')?'classes':'overview';
const navigate=p=>{const target='#/'+p;state.mobile=false;if(location.hash===target)render();else location.hash=target;window.scrollTo({top:0,behavior:'instant'})};
function profileStudent(){const id=route().split('/')[1];return allowedStudents().find(s=>s.id===id)}
const pctChip=p=>p===null?'<span class="chip neutral">No data</span>':`<span class="chip ${p>=95?'good':p>=90?'neutral':'mid'}">${p.toFixed(1)}%</span>`;
const sourceFoot=()=>`<div class="source-strip"><span class="source-pill">Faculty names · My Observations working PLC roster</span><span class="source-pill">Class assignments · fictional</span><span class="source-pill">PowerSchool · simulated</span><span class="source-pill">ManageBac · simulated</span><span class="source-pill">MAP Growth · simulated</span><span class="source-pill">As of 8 Oct 2026</span></div>`;
const personaOptions=selectedId=>['Elementary','Secondary'].map(division=>{
 const members=data.teachers.filter(t=>t.division===division).sort((a,b)=>a.name.localeCompare(b.name,'en'));
 return '<optgroup label="'+esc(division)+' faculty · working PLC roster">'+members.map(t=>'<option value="'+esc(t.id)+'" '+(t.id===selectedId?'selected':'')+'>'+esc(t.name)+' · '+esc(t.primaryPlc)+'</option>').join('')+'</optgroup>';
}).join('');
function shell(body){const section=view(),active=section==='student'?'profile':section;const selected=teacher();app.innerHTML=`<div class="app-shell"><div class="mobile-shade ${state.mobile?'visible':''}" data-dismiss></div><aside class="sidebar ${state.mobile?'mobile-visible':''}"><div class="brand"><img src="./assets/aisg-logo.webp" alt="AISG — American International School of Guangzhou"/><div class="brand-sub"><strong>My Learners</strong><span>UNDERSTAND · CONNECT · SUPPORT</span></div></div><div class="sidebar-group">Workspace</div><button class="navitem ${active==='overview'?'active':''}" data-go="overview">${I('home')} Overview</button><button class="navitem ${active==='classes'?'active':''}" data-go="classes">${I('users')} My Classes</button><button class="navitem ${active==='profile'?'active':''}" ${!profileStudent()?'disabled':''} data-go="${profileStudent()?`student/${profileStudent().id}`:'overview'}">${I('graduate')} Learner Profile</button><div class="sidebar-group">Explore</div><button class="navitem" data-go="classes" data-move="roster">${I('search')} Find a Learner</button><div class="side-bottom"><div class="demo-callout"><strong>● DEMONSTRATION</strong><p>Actual faculty names are from My Observations. Their demo classes, all learners and all learning data are fictional.</p></div><div class="side-footer">AISG | My Learners · Demo 1.0<br/>Inspired by AISG learning and growth.</div></div></aside><div class="main"><header class="topbar"><div class="crumb"><button class="mobile-open" aria-label="Open navigation" data-menu>${I('menu')}</button><span>My Learners</span>${I('arrow',13)}<strong>${section==='overview'?'Overview':section==='classes'?'My Classes':'Learner Profile'}</strong></div><div class="top-right"><label class="top-search">${I('search',16)}<input id="global-search" aria-label="Search learners" placeholder="Find a learner..." autocomplete="off"/></label><label class="sr-only" for="teacher-switch">Switch demonstration teacher</label><select class="persona" id="teacher-switch" aria-label="Demo teacher persona">${personaOptions(selected.id)}</select><span class="demo-badge">DEMO DATA</span></div></header><main class="content" id="main-content">${body}<div class="footer-note">AISG | My Learners · Faculty names from My Observations working PLC roster (not verified HR). All teacher–class assignments and student records are fictional. MAP projections are simulated, not official NWEA values.</div></main></div></div>`;
const search=document.querySelector('#global-search');search?.addEventListener('keydown',ev=>{if(ev.key==='Enter'){state.query=ev.target.value;state.classId='all';navigate('classes');requestAnimationFrame(()=>document.querySelector('#roster-search')?.focus())}})
}
const head=(label,title,subtitle)=>`<div class="page-heading"><div><p class="eyebrow">${esc(label)}</p><h1 class="h1">${esc(title)}</h1>${subtitle?`<p class="subtitle">${esc(subtitle)}</p>`:''}</div><div class="asof">Academic year <strong>${SCHOOL_YEAR}</strong></div></div>`;
const kpi=(label,value,icon,foot)=>`<div class="card kpi"><div class="kpi-top"><span class="kpi-label">${esc(label)}</span><span class="kpi-icon">${I(icon)}</span></div><div class="kpi-value">${esc(value)}</div><div class="kpi-caption">${esc(foot)}</div></div>`;
function overview(){const t=teacher(),students=allowedStudents(),classes=allowedClasses();const attend=avg(students,s=>attendanceSummary(data.attendance[s.id]).rate);const mapStatus=mapGrowthSummary(students.map(s=>s.id),data.map);const assessments=students.reduce((n,s)=>n+data.assessments[s.id].filter(x=>x.status==='Published').length,0);
return `${head('YOUR LEARNING WORKSPACE',`Good afternoon, ${t.name.split(' ')[0]}`,'Explore fictional classes and learning data using real AISG faculty names from the Observations working roster.')}
<div class="hero"><div class="hero-copy"><span class="minor">AISG · PERSONALIZED LEARNING</span><h2>Every learner has a story.<br/>See more of the picture.</h2><p>Explore student strengths, academic growth, attendance and classroom support through one purposeful view.</p></div><div class="hero-art" aria-hidden="true">AISG</div><div class="hero-accent"></div></div>
<div class="kpi-grid">${kpi('My Learners',students.length,'users','Assigned fictional students')}${kpi('My Classes',classes.length,'book','Teaching groups / homerooms')}${kpi('Average Attendance',attend===null?'—':`${attend.toFixed(1)}%`,'calendar','Current year · daily attendance')}${kpi('MAP Growth ≥ Projection',mapStatus.rate===null?'N/A':mapStatus.rate+'%','chart',mapStatus.comparable?`${mapStatus.met} of ${mapStatus.comparable} comparable Fall subject results · simulated`:'No comparable Fall MAP results')}</div>
<div class="dashboard-columns"><section class="card panel"><div class="panel-head"><div><h2 class="section-title">My Classes</h2><p class="section-small">Select a class to explore its learners</p></div><button class="link" data-go="classes">View all ${I('right',14)}</button></div><div class="mini-list">${classes.map(c=>`<button class="class-list-item" data-open-class="${esc(c.id)}"><span class="letter-icon">${esc(c.section)}</span><span class="middle"><strong>${esc(c.name)}</strong><span>${esc(c.campus)} · ${esc(c.division)}</span></span><span class="count">${c.studentIds.length} learners</span>${I('arrow',15)}</button>`).join('')}</div>${classes.length?'':'<p class="note">No classes assigned.</p>'}</section><section class="card panel"><div class="panel-head"><div><h2 class="section-title">Start with understanding</h2><p class="section-small">Questions worth exploring, not automated judgements</p></div></div><div class="info-stack"><div class="insight"><span class="glyph">${I('chart')}</span><div><strong>Growth before achievement</strong><p>How much have learners grown between MAP windows, and what does their progress suggest we might explore?</p></div></div><div class="insight"><span class="glyph">${I('activity')}</span><div><strong>Participation and learning</strong><p>Are there patterns in attendance that merit a supportive conversation?</p></div></div><div class="insight"><span class="glyph">${I('heart')}</span><div><strong>Strengths and support</strong><p>Which adjustments or approaches might help each learner thrive?</p></div></div></div><div class="help-box"><strong>Learning information at a glance</strong><p>${assessments} mock published assessment records are available across your assigned students.</p></div></section></div>${sourceFoot()}`}
const classOption=(c,sel)=>`<option value="${esc(c.id)}" ${sel===c.id?'selected':''}>${esc(c.name)}</option>`;
const cardClass=c=>{const cg=mapGrowthSummary(c.studentIds,data.map,['Mathematics']);return `<button class="big-class ${state.classId===c.id?'active':''}" data-open-class="${esc(c.id)}"><div class="top"><strong>${esc(c.name)}</strong>${I('arrow',16)}</div><div class="numbers"><div><strong>${c.studentIds.length}</strong><span>Learners</span></div><div><strong>${classAttendance(data,c.studentIds).toFixed(1)}%</strong><span>Attendance</span></div><div><strong>${cg.rate===null?'N/A':cg.rate+'%'}</strong><span>Math growth ≥ projection</span></div></div><div class="bottom"><span>${esc(c.campus)}</span><span>Explore class →</span></div></button>`;}
function classesPage(){let cls=allowedClasses(),students=allowedStudents();const grades=[...new Set(cls.map(x=>x.grade))];if(state.grade!=='all')cls=cls.filter(c=>c.grade===state.grade);if(state.classId!=='all')cls=cls.filter(c=>c.id===state.classId);let filtered=students.filter(s=>cls.some(c=>c.id===s.classId));const q=state.query.trim().toLowerCase();if(q)filtered=filtered.filter(s=>[s.name,s.preferred,s.id,s.primaryLanguage].filter(Boolean).some(x=>x.toLowerCase().includes(q)));
return `${head('YOUR CLASSROOMS','My Classes','Move from class-level patterns to an individual learner profile.')}
<div class="card control-bar"><div class="field"><label for="grade-filter">GRADE</label><select id="grade-filter"><option value="all">All assigned grades</option>${grades.map(g=>`<option ${g===state.grade?'selected':''} value="${g}">${gradeDisplay(g)}</option>`).join('')}</select></div><div class="field"><label for="class-filter">CLASS</label><select id="class-filter"><option value="all">All assigned classes</option>${allowedClasses().filter(c=>state.grade==='all'||c.grade===state.grade).map(c=>classOption(c,state.classId)).join('')}</select></div><div class="field search-field"><label for="roster-search">FIND A LEARNER</label><input id="roster-search" value="${esc(state.query)}" placeholder="Search name or demo ID..." autocomplete="off"/></div></div>
${!q?`<div class="classes-cards">${cls.map(cardClass).join('')}</div>`:''}<div class="card roster-wrap"><div class="panel-head" style="padding:20px 20px 0"><div><h2 class="section-title">Learner Roster</h2><p class="section-small">${filtered.length} fictional learners · select a profile to explore details</p></div><span class="demo-badge">SIMULATED</span></div>${filtered.length?`<table class="table"><thead><tr><th>Student</th><th>Class</th><th>Attendance</th><th>MAP Math Growth · Fall 2026</th><th>Assessment</th><th></th></tr></thead><tbody>${filtered.map(s=>{const a=attendanceSummary(data.attendance[s.id]);const map=data.map[s.id].find(x=>x.subject==='Mathematics'&&x.key==='F26');const recent=data.assessments[s.id].find(x=>x.status==='Published');return `<tr><td><div class="student-cell"><img alt="Illustrated portrait of ${esc(s.name)}" loading="lazy" src="${portrait(s.portraitSeed)}"/><div><strong>${esc(s.name)}</strong><small>${esc(s.id)}${s.status==='New to AISG'?' · New learner':''}</small></div></div></td><td>${esc(s.classId)}</td><td>${pctChip(a.rate)}</td><td>${renderGrowthCell(data.map[s.id])}</td><td>${recent?esc(recent.outcome):'Not available'}</td><td><button class="row-button" data-go="student/${s.id}" aria-label="Open ${esc(s.name)} profile">View profile ${I('right',12)}</button></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">'+I('search',32)+'<strong>No learners found</strong><p>Try a different class, grade or search term.</p></div>'}</div>${sourceFoot()}`}
const tabButton=(id,label)=>`<button class="tab ${state.tab===id?'active':''}" data-tab="${id}" role="tab" aria-selected="${state.tab===id}">${label}</button>`;
function profilePage(){const s=profileStudent();if(!s)return `${head('ACCESS SCOPE','Learner not available','Choose a learner from your assigned classes.')}<div class="card empty">${I('shield',38)}<strong>This learner is not in the selected teacher’s demonstration roster.</strong><p>Switch personas or return to My Classes.</p><button class="row-button" data-go="classes">Return to My Classes</button></div>`;
const a=attendanceSummary(data.attendance[s.id]);const m=data.map[s.id].find(x=>x.key==='F26'&&x.subject==='Mathematics');const assess=data.assessments[s.id].find(x=>x.status==='Published');return `<button class="back" data-go="classes">${I('back',14)} Back to My Classes</button><div class="profile-banner"><img class="profile-photo" src="${portrait(s.portraitSeed)}" alt="Fictional illustrated portrait of ${esc(s.name)}"/><div class="profile-copy"><p class="eyebrow">LEARNER PROFILE · ${esc(s.id)}</p><h2>${esc(s.name)}</h2><div class="profile-meta">${esc(gradeDisplay(s.grade))} · ${esc(s.classId)} · ${esc(s.campus)} Campus</div><div class="tag-row"><span class="tag">${esc(s.primaryLanguage)}</span><span class="tag">${s.yearsAtAISG} year${s.yearsAtAISG===1?'':'s'} at AISG</span>${s.status==='New to AISG'?'<span class="tag">New learner</span>':''}</div></div><span class="demo-badge">FICTIONAL PROFILE</span></div><div class="profile-nav" role="tablist" aria-label="Learner profile sections">${tabButton('overview','Overview')}${tabButton('map','MAP Growth')}${tabButton('academic','Academic Learning')}${tabButton('attendance','Attendance')}${tabButton('support','Classroom Support')}</div><div id="profile-content">${state.tab==='overview'?profileOverview(s,a,m,assess):state.tab==='map'?profileMap(s):state.tab==='academic'?profileAcademic(s):state.tab==='attendance'?profileAttendance(s,a):profileSupport(s)}</div>${sourceFoot()}`}
const detail=(name,value)=>`<div class="detail-item"><div class="detail-label">${esc(name)}</div><div class="detail-value">${esc(value)}</div></div>`;
function profileOverview(s,a,m,assess){const mg=latestMapGrowth(data.map[s.id]);return `<div class="profile-kpis">${kpi('Attendance',formatPct(a.rate),'calendar','Current academic year')}${kpi('MAP Math Growth',mg.status==='comparable'?growthFormat(mg.actual)+' pts':'N/A','chart',mg.status==='comparable'?('vs '+growthFormat(mg.projected)+' projected'):'No comparable Fall result')}${kpi('Latest assessment',assess?assess.outcome:'N/A','book','Subject outcome · simulated')}</div><div class="profile-grid"><section class="card panel"><h3 class="section-title">Learner at a Glance</h3><p class="section-small">Essential information for classroom understanding</p><div class="detail-grid">${detail('Preferred name',s.preferred||s.first)}${detail('Grade',gradeDisplay(s.grade))}${detail('Homeroom',s.homeroom)}${detail('Campus',s.campus)}${detail('Primary language',s.primaryLanguage)}${detail('Other languages',s.otherLanguages.join(', ')||'Not recorded')}${detail('Years at AISG',String(s.yearsAtAISG))}${detail('Enrolment status',s.status)}</div><div class="help-box"><strong>Strengths before labels</strong><p>Explore multiple forms of evidence and the classroom context before drawing conclusions about a learner.</p></div></section><section class="card panel"><h3 class="section-title">Quick Context</h3><p class="section-small">Your next conversation, grounded in evidence</p><div class="info-stack" style="margin-top:18px"><div class="insight"><span class="glyph">${I('target')}</span><div><strong>Learning evidence</strong><p>${mg.status==='comparable'?`Simulated Mathematics growth: ${growthFormat(mg.actual)} points versus ${growthFormat(mg.projected)} projected.`:'A comparable Fall Mathematics growth result is not available.'} Explore growth over time.</p></div></div><div class="insight"><span class="glyph">${I('calendar')}</span><div><strong>Participation</strong><p>${a.absences} recorded absent days and ${a.lates} late arrivals in the synthetic school year.</p></div></div><div class="insight"><span class="glyph">${I('shield')}</span><div><strong>Classroom strategies</strong><p>${data.support[s.id].length?`${data.support[s.id].length} fictional support guidance item(s) available.`:'No additional guidance recorded in this demonstration.'}</p></div></div></div></section></div>`}
function mapChart(records){if(!records.length)return '';const W=730,H=245,px=45,py=30,innerW=W-75,innerH=H-65;const values=records.map(x=>x.rit);const lo=Math.floor((Math.min(...values)-8)/10)*10,hi=Math.ceil((Math.max(...values)+8)/10)*10;const y=v=>py+innerH-(v-lo)/(hi-lo||1)*innerH;const x=i=>px+(records.length===1?innerW/2:innerW*i/(records.length-1));const pts=records.map((p,i)=>`${x(i)},${y(p.rit)}`).join(' ');const ticks=Array.from({length:5},(_,i)=>lo+(hi-lo)*i/4);return `<div class="chart-wrap"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Simulated RIT scores over time: ${records.map(r=>r.window+' '+r.rit).join(', ')}"><desc>Line chart of fictional student MAP Growth RIT scores by testing term.</desc>${ticks.map(n=>`<line x1="${px}" y1="${y(n)}" x2="${W-24}" y2="${y(n)}" stroke="#e9eef3" stroke-dasharray="4 4"/><text x="${px-10}" y="${y(n)+4}" font-size="10" text-anchor="end" fill="#94a4b4">${Math.round(n)}</text>`).join('')}<polyline points="${pts}" fill="none" stroke="#0d5681" stroke-width="3.5" stroke-linejoin="round" stroke-linecap="round"/>${records.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.rit)}" r="5.5" fill="#fff" stroke="#0d5681" stroke-width="3"><title>${p.window}: ${p.rit} RIT — simulated</title></circle><text x="${x(i)}" y="${y(p.rit)-13}" font-size="11" font-weight="700" text-anchor="middle" fill="#1d4b6c">${p.rit}</text><text x="${x(i)}" y="${H-12}" font-size="10" text-anchor="middle" fill="#8a9dac">${p.window.replace('Fall ','F').replace('Spring ','S')}</text>`).join('')}</svg></div><p class="chart-caption">RIT scale · Illustrative values only. Percentiles and projections are simulated, not calculated from NWEA norms.</p>`}
function profileMap(s){return renderGrowthProfile(data.map[s.id],state.subject,mapChart)}
function profileAcademic(s){const rows=data.assessments[s.id];return `<section class="card panel"><div class="panel-head"><div><h3 class="section-title">Academic Learning</h3><p class="section-small">Recent classroom assessments · mock ManageBac records</p></div><span class="source-pill">Division-specific scales</span></div><div class="roster-wrap"><table class="table"><thead><tr><th>Assessment</th><th>Subject</th><th>Date</th><th>Status</th><th>Outcome</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.title)}</strong>${x.feedback?'<div class="section-small">Feedback available</div>':''}</td><td>${esc(x.subject)}</td><td>${esc(x.date)}</td><td><span class="chip ${x.status==='Published'?'good':x.status==='Missing'?'red':'neutral'}">${esc(x.status)}</span></td><td>${x.status==='Published'?esc(x.outcome):'—'}</td></tr>`).join('')}</tbody></table></div><div class="help-box"><strong>Assessment context matters</strong><p>Elementary developmental descriptors, MYP-style criteria outcomes and DP-style levels are intentionally presented without converting them into a misleading universal percentage.</p></div></section>`}
function profileAttendance(s,a){const rows=data.attendance[s.id];const months=[...new Set(rows.map(x=>x.date.slice(0,7)))];const byMonth=months.map(month=>{const d=rows.filter(x=>x.date.startsWith(month));return {month:month==='2026-08'?'August':month==='2026-09'?'September':'October',...attendanceSummary(d)}});const exceptions=rows.filter(x=>x.status!=='present').slice(-7).reverse();return `<div class="profile-kpis">${kpi('Attendance Rate',formatPct(a.rate),'calendar','Daily attendance · demo')}${kpi('Absent Days',a.absences,'clock',`${a.total} instructional days`)}${kpi('Late Arrivals',a.lates,'activity','Recorded in demo history')}</div><div class="profile-grid"><section class="card panel"><h3 class="section-title">Attendance by Month</h3><p class="section-small">Consistent with the underlying simulated attendance records</p><div class="attendance-bars">${byMonth.map(x=>`<div class="attendance-bar"><span>${x.month}</span><div class="track"><div class="fill" style="width:${x.rate||0}%"></div></div><strong>${formatPct(x.rate)}</strong></div>`).join('')}</div><div class="help-box"><strong>Participation, not conclusions</strong><p>Attendance records provide context for supportive inquiry. They do not explain the reasons behind an absence or a student's motivation.</p></div></section><section class="card panel"><h3 class="section-title">Recent Attendance Events</h3><p class="section-small">Latest fictional absences and late arrivals</p><div class="attendance-events">${exceptions.length?exceptions.map(e=>`<div class="event"><span>${esc(e.date)}</span><span class="chip ${e.status==='late'?'mid':'neutral'}">${e.status==='late'?'Late arrival':e.excused?'Excused absence':'Unexcused absence'}</span></div>`).join(''):'<p class="note">No absences or late arrivals in this period.</p>'}</div></section></div>`}
function profileSupport(s){const items=data.support[s.id];return `<div class="profile-grid"><section class="card panel"><h3 class="section-title">Classroom Support Guidance</h3><p class="section-small">Practical strategies for classroom access and engagement</p>${items.length?items.map(x=>`<div class="support-card"><div class="support-label">${esc(x.kind)}</div><strong>${esc(x.title)}</strong><p>${esc(x.detail)}</p></div>`).join(''):'<div class="empty">'+I('check',28)+'<strong>No additional guidance recorded</strong><p>Continue using inclusive, responsive Tier 1 teaching strategies.</p></div>'}</section><section class="card panel"><h3 class="section-title">Privacy by Design</h3><p class="section-small">Support students without exposing unnecessary details</p><div class="privacy-box">${I('shield',17)} These are entirely fictional classroom guidance examples. The public demo does not contain medical histories, counselling notes, diagnoses or safeguarding records.</div><div class="help-box"><strong>Production requirement</strong><p>In a live school deployment, access to support guidance must be approved, governed by student-level authorisation and enforced by a secure backend. A public GitHub Pages site cannot protect confidential information.</p></div></section></div>`}
function render(){const previous=document.activeElement;const focusId=previous?.id;let caret=0;try{caret=previous?.selectionStart??0}catch{}
const v=view();if(v!=='student')state.tab='overview';shell(v==='student'?profilePage():v==='classes'?classesPage():overview());if(focusId==='roster-search'){const input=document.getElementById(focusId);if(input){input.focus();input.setSelectionRange(caret,caret)}}}
app.addEventListener('click',e=>{const dismiss=e.target.closest('[data-dismiss]');if(dismiss){state.mobile=false;render();return}const menu=e.target.closest('[data-menu]');if(menu){state.mobile=!state.mobile;render();return}const tab=e.target.closest('[data-tab]');if(tab){state.tab=tab.dataset.tab;render();return}const subject=e.target.closest('[data-subject]');if(subject){state.subject=subject.dataset.subject;render();return}const openClass=e.target.closest('[data-open-class]');if(openClass){state.classId=openClass.dataset.openClass;state.grade='all';state.query='';navigate('classes');return}const nav=e.target.closest('[data-go]');if(nav){if(nav.dataset.move==='roster'){state.classId='all';state.query=''}navigate(nav.dataset.go);return}});
app.addEventListener('change',e=>{if(e.target.id==='teacher-switch'){state.teacherId=e.target.value;localStorage.setItem('aisg-demo-teacher',state.teacherId);state.classId='all';state.grade='all';state.query='';state.tab='overview';navigate('overview')}if(e.target.id==='grade-filter'){state.grade=e.target.value;state.classId='all';render()}if(e.target.id==='class-filter'){state.classId=e.target.value;render()}});
app.addEventListener('input',e=>{if(e.target.id==='roster-search'){state.query=e.target.value;render()}});
window.addEventListener('hashchange',()=>{state.mobile=false;render()});
render();
